FROM alpine:latest

# Metadata (optional but good for showcase)
LABEL maintainer="Krish Kumar Chaurasia"
LABEL description="Dummy Dockerfile for project showcase"

# Just a harmless command
CMD ["echo", "This is a dummy Docker container for showcase. No server is running."]
