FROM alpine:latest

LABEL maintainer="ISHITA SRIVASTAVA"
LABEL description="Dummy Dockerfile for project showcase"

CMD ["echo", "This is a dummy Docker container for showcase. No server is running."]
